<?php

/**
 * @file
 * Autoload.php @generated by Composer.
 */

require_once __DIR__ . '/composer' . '/autoload_real.php';

return ComposerAutoloaderInite1762dac03f6badda12e2d673f7f13dc::getLoader();
