<?php

/**
 * @file
 */

use Composer\Autoload\ClassLoader;

/**
 * @file
 * Autoload_real.php @generated by Composer.
 */
class ComposerAutoloaderInite1762dac03f6badda12e2d673f7f13dc {
  private static $loader;

  /**
   *
   */
  public static function loadClassLoader($class) {

    if ('Composer\Autoload\ClassLoader' === $class) {
      require __DIR__ . '/ClassLoader.php';
    }
  }

  /**
   *
   */
  public static function getLoader() {

    if (NULL !== self::$loader) {
      return self::$loader;
    }

    spl_autoload_register(array('ComposerAutoloaderInite1762dac03f6badda12e2d673f7f13dc', 'loadClassLoader'), TRUE, TRUE);
    self::$loader = $loader = new ClassLoader();
    spl_autoload_unregister(array('ComposerAutoloaderInite1762dac03f6badda12e2d673f7f13dc', 'loadClassLoader'));

    $map = require __DIR__ . '/autoload_namespaces.php';
    foreach ($map as $namespace => $path) {
      $loader->set($namespace, $path);
    }

    $map = require __DIR__ . '/autoload_psr4.php';
    foreach ($map as $namespace => $path) {
      $loader->setPsr4($namespace, $path);
    }

    $classMap = require __DIR__ . '/autoload_classmap.php';
    if ($classMap) {
      $loader->addClassMap($classMap);
    }

    $loader->register(TRUE);

    return $loader;
  }

}
